# Generated by Django 2.2.28 on 2022-06-28 05:31

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20220625_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(max_length=300, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='profile-images/default/user.png', upload_to=profile.models.image_directory_path, verbose_name='user_image'),
        ),
    ]
