# Generated by Django 2.2.28 on 2022-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20220628_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロフィール', 'verbose_name_plural': 'プロフィール群'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(max_length=500, verbose_name='introduction'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
