# Generated by Django 2.2.28 on 2022-06-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=250, verbose_name='hobby')),
                ('introduction', models.CharField(max_length=300, verbose_name='introduction')),
                ('user_image', models.ImageField(default='media/user-icon/default/user.png', upload_to=profile.models.image_directory_path, verbose_name='user_image')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
