# Generated by Django 2.2.28 on 2022-06-29 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='外部講師の属する企業名を登録して下さい。', max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company群',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='ITLGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ITLグループ',
                'verbose_name_plural': 'ITLグループ群',
                'db_table': 'ITL Group',
            },
        ),
        migrations.CreateModel(
            name='Traineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default='no-company', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_traineer', to='accountManagement.Company')),
                ('traineer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'トレーナー',
                'verbose_name_plural': 'トレーナー群',
                'db_table': 'user_traineer',
            },
        ),
        migrations.CreateModel(
            name='ITLGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountManagement.ITLGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ITLグループユーザー',
                'verbose_name_plural': 'ITLグループユーザー群',
                'db_table': 'ITL Group User',
            },
        ),
    ]
