# Generated by Django 2.2.28 on 2022-07-04 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0002_itlgroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itlgroupuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
