# Generated by Django 2.2.28 on 2022-07-04 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0003_auto_20220704_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itlgroupuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
