# Generated by Django 2.2.28 on 2022-06-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(max_length=300, verbose_name='description')),
                ('company', models.ForeignKey(default='no-company', on_delete=django.db.models.deletion.SET_DEFAULT, to='accountManagement.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTraineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Traineer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Training')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(max_length=500, verbose_name='memo')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountManagement.ITLGroup')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Training')),
            ],
        ),
    ]
