# Generated by Django 2.2.28 on 2022-06-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20220629_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='memo'),
        ),
    ]
