# Generated by Django 2.2.28 on 2022-07-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialy', '0002_auto_20220705_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialy',
            old_name='satisfactionLevel',
            new_name='understandScore',
        ),
    ]
