# Generated by Django 2.2.28 on 2022-07-06 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialy', '0003_auto_20220705_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
