# Generated by Django 2.2.28 on 2022-06-16 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220616_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('is_staff', models.BooleanField(default=True, verbose_name='is_staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_traineer', models.BooleanField(default=False, verbose_name='is_traineer')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date time')),
            ],
            options={
                'verbose_name': 'ITLスタッフ',
                'verbose_name_plural': 'ITLスタッフ群',
                'db_table': 'staff_model',
            },
        ),
    ]
