# Generated by Django 2.2.28 on 2022-06-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220624_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='あなたの名を英字で入力してください。', max_length=150, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='あなたの姓を英字で入力してください。', max_length=150, verbose_name='last_name'),
        ),
    ]
