# Generated by Django 2.2.28 on 2022-06-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220624_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='アカウントが使えるようになるにはTrueにしてください。', verbose_name='is_active'),
        ),
    ]
