# Generated by Django 2.2.28 on 2022-06-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220624_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='アプリを利用するためにはTrueにしてください', verbose_name='is_activated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Falseにすると、アカウントとして認められません。', verbose_name='is_active'),
        ),
    ]
